config/routes.rb
Tunr::Application.routes.draw do
  resources :artists, only: [:index, :show]
  resources :songs, only: [:show] do
    member do
      post 'purchase'
    end
  end

  resources :users, except: [:index]

  resource :session, only: [:new, :create, :destroy]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :balance, numericality: { greater_than_or_equal_to: 0 }
  has_and_belongs_to_many :songs

  has_secure_password

  def purchase(song)
    if afford?(song) && pay_for(song)
      self.songs << song
    end
  end

  def afford?(song)
    balance >= song.price
  end

  def pay_for(song)
    self.balance -= song.price
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    # authenticate that user/pass combo is legit
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(artists_path)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticated!, only: [:purchase]

  def show
    @song = Song.find(params[:id])
  end

  def purchase
    @song = Song.find(params[:id])

    if current_user.purchase(@song)
      redirect_to user_path(current_user)
    else
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticated!, :set_user, :authorized!, except: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to new_user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authorized!
    unless @user.id == session[:user_id]
      redirect_to user_path(session[:user_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id].present?
  end

  def authenticated!
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/artists/index.html.erb
<h1>Artists:</h1>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<p>Songs:</p>
<ul>
  <% @artist.songs.each do |song| %>
    <li><%= link_to song.name, song_path(song) %></li>
  <% end %>
</ul>

<%= link_to "Back", artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <% if logged_in? %>
      <ul>
        <li><%= link_to 'Logout', session_path, :method => :delete %></li>
      </ul>
    <% end %>
  </nav>

<%= yield %>

</body>
</html>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>
<p>Artist: <%= @song.artist.name %> </p>

<iframe src="https://embed.spotify.com/?uri=<%= @song.spotify_uri %>" width="300" height="380" framborder="0" allowtransparency="true"></iframe>

<% if logged_in? %>
  <%= link_to 'Purchase', purchase_song_path(@song), :method => :post %>
<% end %>

<%= link_to "Back", artist_path(@song.artist) %>

app/views/users/_form.html.erb
<% unless @user.errors.none? %>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing <%= @user.email %></h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<%= link_to "Edit", edit_user_path(@user) %> |
<%= link_to "Destroy", user_path(@user), :method => :delete %>

<h3>Songs:</h3>
<ul>
  <% @user.songs.each do |song| %>
    <li><%= link_to song.name, song_path(song) %></li>
  <% end %>
</ul>